spring:
  # Embedded ActiveMQ Configuration Example
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: false
      trusted: org.learning
  # Spring JMS Settings
  jms:
    pub-sub-domain: true
    template:
      delivery-mode: persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 360000

