spring:
  # Embedded ActiveMQ Configuration Example
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: false
      trusted: org.learning
    pool:
      block-if-full: true
      block-if-full-timeout: -1
      enabled: false
      idle-timeout: 30000
      max-connections: 1
      time-between-expiration-check: -1
      use-anonymous-producers: true
  # Spring JMS Settings
  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true
    pub-sub-domain: false
    template:
      default-destination: order-queue
      delivery-mode: non_persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 360000

